docs = [
    # --- COFFEE (negation + overlap) ---
    "This coffee is good",
    "This coffee is not good",
    "This coffee tastes good",
    "This coffee tastes bad",
    "This coffee is not bad",
    "I like this coffee",
    "I do not like this coffee",
    "I love this coffee",
    "I do not love this coffee",
    "The coffee is amazing",
    "The coffee is not amazing",
    "The coffee is terrible",
    "The coffee is not terrible",
    "This coffee smells good but tastes bad",
    "This coffee tastes good but smells bad",

    # --- PRODUCT (ambiguous + negation) ---
    "This product works well",
    "This product does not work well",
    "This product works",
    "This product does not work",
    "The product is good",
    "The product is not good",
    "The product is bad",
    "The product is not bad",
    "The product is okay",
    "The product is not okay",
    "This product is fine",
    "This product is not fine",
    "It works but not as expected",
    "It does not work as expected",

    # --- SERVICE / EXPERIENCE ---
    "The service is excellent",
    "The service is not excellent",
    "The service is bad",
    "The service is not bad",
    "The experience was good",
    "The experience was not good",
    "The experience was bad",
    "The experience was not bad",
    "The experience was okay",
    "The experience was not okay",

    # --- MIXED / TRICKY SENTENCES ---
    "The product is good but not great",
    "The product is bad but not terrible",
    "The coffee is good but not strong",
    "The coffee is strong but not good",
    "This is okay, not great",
    "This is not great but okay",
    "I expected more but it is not bad",
    "I expected less but it is not good",
    "It is fine but not impressive",
    "It is impressive but not perfect",

    # --- EDGE CASES (confusing semantics) ---
    "Not bad at all",
    "Not good at all",
    "It is not uncommon",
    "It is not unusual",
    "It is hardly good",
    "It is barely bad",
    
    # HARD CONFUSION CASES
    "Not good but not bad either",
    "Good but not really good",
    "Bad but not that bad",
    "Not terrible but not good",
    "Works but not properly",
    "Does not fail but does not succeed",
    "Acceptable but not satisfying",
    "Not unacceptable",
    "Not entirely good",
    "Not entirely bad",
]